package org.example.blackjack.unit;

unit BlackjackUnit;

rule "Il giocatore vince con Blackjack"
when
    $t: /turn[phase == Phase.PAYOUT, result == Result.WIN]
    $p: /player[handValue == 21, hand.size == 2, $b: bet, $bal: balance]
then
    double totalBalance = $bal + ($b * 2.5);
    modify($p){
        setBalance(totalBalance)
    }
    modify($t){
        setPhase(Phase.RESET)
    }
    events.add("Player wins with a Blackjack! Payout is 3:2.");
end

rule "Il giocatore vince "
when
    $t: /turn[phase == Phase.PAYOUT, result == Result.WIN]
    $p: /player[$b: bet, $bal: balance]
then
    double totalBalance = $bal + ($b * 2);
    modify($p){
        setBalance(totalBalance)
    }
    modify($t){
            setPhase(Phase.RESET)
        }
    events.add("Player wins ");
end

rule "Il giocatore ha perso"
when
    $t: /turn[phase == Phase.PAYOUT, result == Result.LOSE]
    $p: /player
then
    modify($t){
        setPhase(Phase.RESET)
    }
    events.add("Player loses.");
end

rule "Pareggio"
when
    $t: /turn[phase == Phase.PAYOUT, result == Result.TIE]
    $p: /player[$b: bet, $bal: balance]
then
    double totalBalance = $b + $bal;

    modify($p){
        setBalance(totalBalance)
    }

    modify($t){
        setPhase(Phase.RESET)
    }
    events.add("It's a tie! Player's bet is returned.");
end