package org.example.blackjack.unit;

unit BlackjackUnit;

import java.util.ArrayList;

rule "Reset del turno"
when
    $t: /turn[phase == Phase.RESET]
    $p: /player
    $d: /dealer
then
    modify($p){
        setHand(new ArrayList<>()),
        setBet(0)
    }

    modify($d){
        setHand(new ArrayList<>())
    }

    modify($t){
        setResult(Result.NONE),
        setPhase(Phase.BET)
    }
end
