package org.example.briscola.unit;

unit BriscolaUnit;

import org.example.briscola.model.*;

rule "assegna 3 carte ad ogni giocatore"
when
    $t: /turn[phase == Phase.SETUP, $ap: activePlayer]
    $p: /players[name == $ap, hand.size == 0]
then
    modify($p){
        setHand(deck.draw(3))
    }
    modify($t){
        setActivePlayer(dealer.getNextPlayer($ap))
    }
end

rule "rivela la briscola"
when
    $t: /turn[phase == Phase.SETUP, briscola == null]
    forall(/players[hand.size == 3])
then
    BriscolaCard briscola = deck.draw();
    modify($t){
        setBriscola(briscola)
    }
    events.add("[BRISCOLA] : " + briscola);
end

rule "avanza alla fase di gioco"
when
    $t: /turn[phase == Phase.SETUP, briscola != null]
then
    modify($t){
        setPhase(Phase.EVALUATE)
    }
end
