package org.example.briscola.unit;

unit BriscolaUnit;

rule "rimuovi carte dal tavolo"
when
    $t: /turn[phase == Phase.RESET]
    $cardPlayed: /table
then
    table.remove($cardPlayed);

    events.add("[RESET] - Card: " + $cardPlayed.getCard() + " removed from table");
end

rule "reinserire giocatori al tavolo"
when
    $t: /turn[phase == Phase.RESET]
    $defeated: /defeats
then
    defeats.remove($defeated);
    players.add($defeated);

    events.add("[RESET] - " + $defeated.getName() + " re-enters the game");
end

rule "tutti i giocatori sono rientrati e il tavolo è vuoto, si passa alla fase di pesca"
when
    $t: /turn[phase == Phase.RESET]
    not /table
    not /defeats
then
    modify($t){ setPhase(Phase.DRAW) }

    events.add("[RESET] - All players are back, starting new round");
end